### ISSUE TITLE
keyDB is going to opensource it's rocksDB support

### ISSUE THREAD

**Issue by raphaelauv** [szstonelee/redrock#2]
https://docs.keydb.dev/docs/coming-soon#keydb-flash-support

```
Support for KeyDB FLASH using the RocksDB engine will become available September 2022
```

what do you think about that news ?

**Comment by szstonelee** [comment]
I never use KeyDB. But from the news, it seems KeyDB is compatible with Redis Commands and data structure and try  to solve the same problem -- extending to disk. So I am glad there are many solutions for the same feature. Actually Redis Lab also support Flash disk but not open sourced (so no free because the feature is for the Enterprise edition of Redis only).

 I recommend to try every tools and select the best one for the clients' situation. 
 
 By the way, for the RAFT feature, BunnyRedis I coded is another alternative solution (KeyDB and Redis Lab's Reids Enterprise also have the similar solutions).  You  can try it.
 
 Good luck.

**Comment by raphaelauv** [comment]
Yes keydb is a fork of redis so it's almost 100% compatible.

Thanks for your answer :+1
